FROM node:16-alpine

WORKDIR /usr/app

COPY package.json .
RUN npm install
# Here we do not COPY command as source code is already present in local and not in container
COPY . .

CMD ["npm", "run" ,"start"]